# docker-compose up –build
# Access main page http://127.0.0.1/
# Access to Postgres Admin http://127.0.0.1:8081/

version: "3.7"
services:
    rails:
        build: .
        image: backbone_on_rails #Name of the image built by the build instruction
        volumes:
            - ./backbone_test/:/backbone_on_rails
        ports: 
            - "80:3000"
